name: Emulator Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  emulator-tests:
    runs-on: ubuntu-latest
    # Only run on main branch pushes or manual triggers to save CI resources
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create secrets.properties
      run: |
        echo "TRAKT_API_KEY=${{ secrets.TRAKT_API_KEY }}" >> secrets.properties
        echo "OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}" >> secrets.properties
        echo "TMDB_READ_KEY=${{ secrets.TMDB_READ_KEY }}" >> secrets.properties
        
    - name: Build debug APK
      run: ./gradlew assembleDebug
        
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        
    - name: Run Android TV emulator tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: tv_1080p
        emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
        disable-animations: true
        script: |
          # Wait for emulator to fully boot
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
          
          # Install the app
          echo "Installing app..."
          adb install app/build/outputs/apk/debug/app-debug.apk
          
          # Launch the app
          echo "Launching app..."
          adb shell am start -n com.strmr.ai/.MainActivity
          sleep 5
          
          # Take a screenshot
          echo "Taking screenshot..."
          adb shell screencap -p /sdcard/screenshot.png
          adb pull /sdcard/screenshot.png screenshot-launch.png
          
          # Check if app is running
          if adb shell ps | grep -q com.strmr.ai; then
            echo "✅ App is running successfully"
          else
            echo "❌ App failed to start"
            adb logcat -d > logcat-failure.txt
            exit 1
          fi
          
          # Test DPAD navigation
          echo "Testing DPAD navigation..."
          adb shell input keyevent 20  # DPAD_DOWN
          sleep 1
          adb shell input keyevent 22  # DPAD_RIGHT
          sleep 1
          adb shell screencap -p /sdcard/screenshot-nav.png
          adb pull /sdcard/screenshot-nav.png screenshot-navigation.png
          
          echo "✅ Basic smoke tests completed"
          
    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: emulator-screenshots
        path: "*.png"
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: emulator-logs
        path: "*.txt"